---
- hosts: localhost
  remote_user: ubuntu
  become: yes
  gather_facts: no
  
  pre_tasks:  #install all of this on the new server:

    - name: Update repositories cache
      become: yes
      apt:
        update_cache: yes    

    - name: 'install curl'
      retries: 5
      become: yes
      shell: 'apt-get -y install curl'

    - name: mkdir for the armor files
      shell: mkdir -p /home/ubuntu/armor

    - name: install the armor agent
      shell: sudo curl -sSL https://agent.armor.com/latest/armor_agent.sh | sudo bash /dev/stdin -l AAAA1-AAAA1-AAAA1-AAAA1-AAAA1 -r us-west-armor -f

###---
